name: Industry Matcher

on:
  schedule:
    # 每小时运行一次（整点）
    - cron: '0 * * * *'
  workflow_dispatch:  # 允许手动触发
    inputs:
      limit:
        description: 'Maximum number of news to process'
        required: false
        default: ''
        type: string

jobs:
  match-industries:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run industry matcher
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GEMINI_MODEL: ${{ vars.GEMINI_MODEL || 'gemini-2.0-flash-lite' }}
      run: |
        if [ -n "${{ github.event.inputs.limit }}" ]; then
          echo "Running with limit: ${{ github.event.inputs.limit }}"
          python -c "import sys; sys.path.insert(0, 'src'); from industry_matcher import IndustryMatcher; matcher = IndustryMatcher(); matcher.run(limit=${{ github.event.inputs.limit }})"
        else
          echo "Running without limit"
          python -c "import sys; sys.path.insert(0, 'src'); from industry_matcher import IndustryMatcher; matcher = IndustryMatcher(); matcher.run()"
        fi
    
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: matcher-logs-${{ github.run_number }}
        path: |
          *.log
        retention-days: 7